#!/bin/bash
##PBS -V
#PBS -l nodes=1:ppn=1,walltime=160:00:00
##PBS -l partition=beacon
#PBS -l advres=condo-staff.13774103
#PBS -A ACF-STA0006
#PBS -l qos=staff
#PBS -N combine
#PBS -o log/$PBS_JOBNAME-o$PBS_JOBID
#PBS -e log/$PBS_JOBNAME-e$PBS_JOBID


cd $PBS_O_WORKDIR

echo "started at " `date`

for pdfsplit in *
do
    if [ -d "$pdfsplit" ] && [[ "$pdfsplit" == "split"* ]]; then
        sh combine_txt_batch.sh $pdfsplit
    fi
done

echo "completed! at " `date`
